package code.T6practicas.Clases;

public class Trabajador2Herencia extends code.Unidad6ClasesHerencia.Persona 
{
    public Trabajador2Herencia(String nombre, int edad)
    {
        super(nombre,edad);
        this.edad = 33;

        //Todo autogenerated contructor.

        Persona p1 = new code.Unidad6ClasesHerencia.Persona("Pablo");
    }
    
}
